services:
  postgres:
    image: postgres:16-alpine
    container_name: modumart-postgres
    environment:
      POSTGRES_DB: modumart
      POSTGRES_USER: modumart
      POSTGRES_PASSWORD: modumart123
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --lc-collate=C --lc-ctype=C"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - modumart-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U modumart -d modumart"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
    driver: local

networks:
  modumart-network:
    driver: bridge