spring:
  application:
    name: modumart

  datasource:
    url: jdbc:postgresql://localhost:5432/modumart
    username: ${DB_USERNAME:modumart}
    password: ${DB_PASSWORD:modumart123}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: ${SHOW_SQL:false}
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: true
    drop-first: false

  modulith:
    events:
      jdbc:
        schema-initialization:
          enabled: true
      completion-update-interval: PT1M
      incomplete-events-cleanup-interval: PT1H
      retention-duration: P7D

  task:
    execution:
      pool:
        core-size: 4
        max-size: 16
        queue-capacity: 100
    scheduling:
      pool:
        size: 4

# Logging configuration for better event monitoring
logging:
  level:
    org.springframework.modulith: ${MODULITH_LOG_LEVEL:INFO}
    com.negadras.modumart: ${APP_LOG_LEVEL:INFO}
    org.springframework.modulith.events: DEBUG
  pattern:
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n%wEx"

# Management endpoints for monitoring
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,modulith
  endpoint:
    health:
      show-details: when_authorized
    modulith:
      enabled: true
