name: Database Migration Validation

on:
  push:
    paths:
      - 'src/main/resources/db/**'
      - 'pom.xml'
  pull_request:
    paths:
      - 'src/main/resources/db/**'
      - 'pom.xml'
  workflow_dispatch:

env:
  JAVA_VERSION: '24'
  MAVEN_OPTS: -Dhttp.keepAlive=false -Dmaven.wagon.http.pool=false -Dmaven.wagon.http.retryHandler.class=standard -Dmaven.wagon.http.retryHandler.count=3

jobs:
  validate-migrations:
    name: Validate Liquibase Migrations
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_PASSWORD: testpass
          POSTGRES_USER: testuser
          POSTGRES_DB: modumart_test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 24
        uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: 'oracle'

      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Validate changelog syntax
        run: mvn liquibase:validate
        env:
          SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/modumart_test
          SPRING_DATASOURCE_USERNAME: testuser
          SPRING_DATASOURCE_PASSWORD: testpass

      - name: Check for changelog formatting
        run: |
          echo "Checking changelog files for proper formatting..."
          find src/main/resources/db/changelog -name "*.yaml" -o -name "*.yml" | while read file; do
            if ! yamllint "$file"; then
              echo "❌ YAML formatting error in $file"
              exit 1
            fi
          done
          echo "✅ All changelog files are properly formatted"

      - name: Run migration on clean database
        run: mvn liquibase:update
        env:
          SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/modumart_test
          SPRING_DATASOURCE_USERNAME: testuser
          SPRING_DATASOURCE_PASSWORD: testpass

      - name: Generate database documentation
        run: mvn liquibase:dbDoc
        env:
          SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/modumart_test
          SPRING_DATASOURCE_USERNAME: testuser
          SPRING_DATASOURCE_PASSWORD: testpass

      - name: Upload database documentation
        uses: actions/upload-artifact@v4
        with:
          name: database-documentation
          path: target/liquibase/dbDoc/

  test-rollback:
    name: Test Migration Rollback
    runs-on: ubuntu-latest
    needs: validate-migrations

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_PASSWORD: testpass
          POSTGRES_USER: testuser
          POSTGRES_DB: modumart_rollback_test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 24
        uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: 'oracle'

      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Apply all migrations
        run: mvn liquibase:update
        env:
          SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/modumart_rollback_test
          SPRING_DATASOURCE_USERNAME: testuser
          SPRING_DATASOURCE_PASSWORD: testpass

      - name: Test rollback capability
        run: |
          echo "Testing rollback of last 3 changesets..."
          mvn liquibase:rollback -Dliquibase.rollbackCount=3
        env:
          SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/modumart_rollback_test
          SPRING_DATASOURCE_USERNAME: testuser
          SPRING_DATASOURCE_PASSWORD: testpass
        continue-on-error: true

      - name: Re-apply migrations after rollback
        run: mvn liquibase:update
        env:
          SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/modumart_rollback_test
          SPRING_DATASOURCE_USERNAME: testuser
          SPRING_DATASOURCE_PASSWORD: testpass

  schema-drift-detection:
    name: Schema Drift Detection
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'

    services:
      postgres-baseline:
        image: postgres:15
        env:
          POSTGRES_PASSWORD: testpass
          POSTGRES_USER: testuser
          POSTGRES_DB: modumart_baseline
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

      postgres-current:
        image: postgres:15
        env:
          POSTGRES_PASSWORD: testpass
          POSTGRES_USER: testuser
          POSTGRES_DB: modumart_current
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5433:5432

    steps:
      - name: Checkout baseline (main branch)
        uses: actions/checkout@v4
        with:
          ref: main
          path: baseline

      - name: Checkout current branch
        uses: actions/checkout@v4
        with:
          path: current

      - name: Set up JDK 24
        uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: 'oracle'

      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Apply baseline migrations
        run: |
          cd baseline
          mvn liquibase:update
        env:
          SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/modumart_baseline
          SPRING_DATASOURCE_USERNAME: testuser
          SPRING_DATASOURCE_PASSWORD: testpass

      - name: Apply current migrations
        run: |
          cd current
          mvn liquibase:update
        env:
          SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5433/modumart_current
          SPRING_DATASOURCE_USERNAME: testuser
          SPRING_DATASOURCE_PASSWORD: testpass

      - name: Generate schema diff report
        run: |
          cd current
          mvn liquibase:diff \
            -Dliquibase.referenceUrl=jdbc:postgresql://localhost:5432/modumart_baseline \
            -Dliquibase.referenceUsername=testuser \
            -Dliquibase.referencePassword=testpass
        env:
          SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5433/modumart_current
          SPRING_DATASOURCE_USERNAME: testuser
          SPRING_DATASOURCE_PASSWORD: testpass

      - name: Upload diff report
        uses: actions/upload-artifact@v4
        with:
          name: schema-diff-report
          path: current/target/liquibase/migrate.sql